version: "3"
services:
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    ports:
      - 8080:80
  webapp-with-opcahce:
    build:
      context: webapp
      dockerfile: Dockerfile-with-opcahce
    ports:
      - 8081:80
  webapp-with-opcahce-redis:
    build:
      context: webapp
      dockerfile: Dockerfile-with-opcahce-redis
    ports:
      - 8082:80
  redis:
    image: redis
